services:
  db:
    image: 'postgres:latest'
    container_name: db_cont
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-networks
    volumes:
      - ./../MyBankProject/db-data/:/var/lib/postgresql/data/
      
  app:
    container_name: tgbot_cont
    ports:
      - 2266:2266
    build: .
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - postgres-networks
    volumes:
      - ./files:/bankAPI/files

networks:
  postgres-networks:
    driver: bridge