services:
  app:
    container_name: tgbot_cont
    ports:
      - 2265:2265
    build: .
    env_file:
      - .env
    networks:
      - mybankproject_postgres-networks
    volumes:
      - ./../MyBankProject/files:/tgApp/files

networks:
  mybankproject_postgres-networks:
     external: true