services:
  app:
    container_name: tgbot_cont
    ports:
      - 2265:2265
    build: .
    env_file:
      - .env
    networks:
      - postgres-networks
    volumes:
      - ./../MyBankProject/files:/tgApp/files

networks:
  postgres-networks:
    external: true